inherit_from:
  - .rubocop_marvel_comics_explorer.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "bin/*"
    - "tmp/**/*"
    - "spec/files/*"
    - "Rakefile"
